AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - tmp/**/*
    - lib/bundler/vendor/**/*
  DisplayCopNames: true

# Lint

Lint/ScriptPermission:
  Enabled: true
  Exclude:
    - 'lib/bundler/templates/Executable'

# Layout

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/SpaceInsideBlockBraces:
  Enabled: true
  SpaceBeforeBlockParameters: false

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

# Style

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# We adopted raise instead of fail.
Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# 1.8.7 support

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets
